#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3    


bspc config border_width         5
bspc config window_gap          50
bspc config focused_border_color "#f38ba8"
bspc config normal_border_color "#1e1e2e"
bspc config top_padding          30

 
